services:
  shieldx-db:
    image: mongo:latest
    container_name: shieldx-db
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  shieldx-broker:
    image: rabbitmq:4.0-management
    container_name: shieldx-broker
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    restart: unless-stopped

  shieldx-api:
    image: ${API_IMAGE}
    container_name: shieldx-api
    depends_on:
      - shieldx-db
      - shieldx-broker
    ports:
      - "${API_PORT}:20000"
    volumes:
      - ./logs:/app/log
    restart: unless-stopped

volumes:
  mongo-data:
